# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Antonios Hadjigeorgalis
email: Antonios@Hadji.co
description: > # this means to ignore newlines until "baseurl:"
  Entrepreneur, philosopher, scientist.</br>
  Constantly striving to improve everything I touch.</br>
  Business, technology, mind & body power
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.hadji.co" # the base hostname & protocol for your site
twitter_username: AntoniosHadji
github_username:  AntoniosHadji
linkedin_username: AntoniosHadji
google-plus_username: AntoniosHadjigeorgalis
disqusid: antonioshadji
# Build settings
markdown: kramdown

permalink: :title/
