# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# Jekyll theme
# https://github.com/jekyll/minima
# this is the default theme that you get with jekyll new command

# Site settings
title: Antonios Hadjigeorgalis
email: Antonios@Hadji.co
description: > # this means to ignore newlines until "baseurl:"
  Entrepreneur+Engineer</br>
  Constantly striving to improve everything I touch:</br>
  Business strategy, technology solutions, cognitive & physical performance
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.hadji.co" # the base hostname & protocol for your site
permalink: /:title/

# Social settings
twitter_username: AntoniosHadji
github_username:  AntoniosHadji
linkedin_username: AntoniosHadji
google-plus_username: AntoniosHadjigeorgalis
disqusid: antonioshadji

# Build settings
markdown: kramdown

# Gems
plugins:
  - jekyll-feed

# Collection settings
collections:
  books:
    output: true

